/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car_rental;

/**
 *
 * @author 63966
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        car1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        car2 = new javax.swing.JButton();
        car3 = new javax.swing.JButton();
        car4 = new javax.swing.JButton();
        car5 = new javax.swing.JButton();
        car6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(870, 600));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(870, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fast 5 Car Rental");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Car Selections");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        car1.setBackground(new java.awt.Color(0, 0, 0));
        car1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rental/1.jpg"))); // NOI18N
        car1.setAlignmentY(0.0F);
        car1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        car1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(car1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 200, 120));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Group C - Sedan Automatic Transmission");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Group F - Commercial Van");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, -1, -1));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Group B - Sedan Manual transition");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mini cars - All Automatic");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Group D - MPV");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Group E - SUV");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, -1, -1));

        car2.setBackground(new java.awt.Color(0, 0, 0));
        car2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rental/2.jpg"))); // NOI18N
        car2.setAlignmentY(0.0F);
        car2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        car2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(car2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 200, 120));

        car3.setBackground(new java.awt.Color(0, 0, 0));
        car3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rental/3.jpg"))); // NOI18N
        car3.setAlignmentY(0.0F);
        car3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        car3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(car3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 200, 120));

        car4.setBackground(new java.awt.Color(0, 0, 0));
        car4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rental/4.jpg"))); // NOI18N
        car4.setAlignmentY(0.0F);
        car4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        car4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(car4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 200, 120));

        car5.setBackground(new java.awt.Color(0, 0, 0));
        car5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rental/5.jpg"))); // NOI18N
        car5.setAlignmentY(0.0F);
        car5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        car5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(car5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 200, 120));

        car6.setBackground(new java.awt.Color(0, 0, 0));
        car6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rental/6.jpg"))); // NOI18N
        car6.setAlignmentY(0.0F);
        car6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        car6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(car6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 200, 120));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Register a car for RENT");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton car1;
    private javax.swing.JButton car2;
    private javax.swing.JButton car3;
    private javax.swing.JButton car4;
    private javax.swing.JButton car5;
    private javax.swing.JButton car6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
